### ISSUE TITLE
Why each iteration can yield data for lookback_window days?

### ISSUE THREAD

**Issue by jianzhang-happy** [SJTU-Quant/MASTER#1]
Hello. Thank you for your outstanding work. While running your code, I have a small question: I'm curious about why the dataset obtained after running the iteration of DataLoader is four-dimensional (1*N*T*F). My main concern is how the time dimension T is introduced here. I noticed that the data type you provided is "qlib.data.dataset.TSDataSampler," and by referring to qlib's source code and the PyTorch official tutorial, I understand that this is a map-style dataset data type similar to PyTorch. When using DataLoader, it seems that the iterator of the Sampler you use returns data for only one day each time, rather than data for the lookback_window (8) days. Therefore, I am a bit confused about how each iteration can yield data for lookback_window days. I hope to receive your response, and once again, thank you!

**Comment by jianzhang-happy** [comment]
I think I have understood the reasons now. Thanks again for your outstanding work!

**Comment by keyboard1st** [comment]
I have the same problem as you.Can you tell me why each iteration can yield data for lookback_window days?Thank you for your response!
