### ISSUE TITLE
Bug in code?

### ISSUE THREAD

**Issue by soya-git** [SJTU-Quant/MASTER#15]
![image](https://github.com/SJTU-Quant/MASTER/assets/126449058/6e4cf572-0509-4d61-8e61-7db23d804aee)
In baseline.py, line167, shouldn't it be 'RICIR' : np.mean(**ric**)/np.std(ric)?

**Comment by LITONG99** [comment]
Thank you for pointing this out and allow me to apologize for the trouble and confusion.

You are right. We have fixed it in the [new commit on master branch](https://github.com/SJTU-Quant/MASTER/tree/eb937cb26fb15841dc48456c2e78a6096ac2e25c), which only changes this line to `np.mean(ric)/np.std(ric)`.
