### ISSUE TITLE
about the result of ric and ricir

### ISSUE THREAD

**Issue by happyday258** [SJTU-Quant/MASTER#16]
when I use the dataset and the model you offer, I get the ric and ricir in the test dataset which is much worse than your paper display,
can you explain for me ? thanks. my ric and ricir are 'RIC': 0.034360794294788645, 'RICIR': 0.26788646356158735

**Comment by LITONG99** [comment]
It seems you are not running the code correctly. Here is the results: 
<img width="996" alt="1721904538515" src="https://github.com/user-attachments/assets/8309d899-c32c-49e8-8b13-4310834aa547">

Could you please double-check to make sure the model and data are correct and complete?
