### ISSUE TITLE
Dataset code

### ISSUE THREAD

**Issue by w1nn1ethepooh** [SJTU-Quant/MASTER#3]
Thank you for your fancy job!

I would like to ask if there is any source of code for generating the data sets dl_train, dl_valid and dl_test.

Have a nice day!

**Comment by LITONG99** [comment]
Thank you for your attention to our work.
We are not planning to publish the data infrastructure for explained reasons. If you need to process raw data,  we highly recommend reusing the Qlib implementations. Here is the configuration: 

> infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
         kwargs:
              fields_group: feature
learn_processors:
        - class: DropnaLabel
        - class: DropExtremeLabel
        kwargs: 
		percentile: 0.975
	- class: CSZscoreNorm
          kwargs:
              fields_group: label

Please note that, except for `DropExtremeLabel`, the above configuration is used for many models in `qlib/examples/benchmarks` and we do use the Qlib implementations in producing the published dl_train, dl_valid, and dl_test. The `DropExtremeLabel` is implemented in our commercial codebase, which should be easy to implement in Qlib as well, since it obeys a simple rule to drop 2.5% of the highest/lowest labels.

**Comment by ElonJustin7** [comment]
Hi, thank you for your outstanding work! 
<img width="536" alt="mask" src="https://github.com/SJTU-Quant/MASTER/assets/129352610/50742c01-6a04-41a5-9e59-5edfbdce604b">
 I'd like to ask about the "Mask" in the information regarding market indices (such as 000300) in your dataset. What does it refer to? Thank you!

**Comment by caozhiy** [comment]
I think it is a Qlib data operator 'qlib.data.ops.Mask'. You can refer to https://qlib.readthedocs.io/en/latest/reference/api.html#module-qlib.data.ops for more details.

> Hi, thank you for your outstanding work! <img alt="mask" width="536" src="https://private-user-images.githubusercontent.com/129352610/317664554-50742c01-6a04-41a5-9e59-5edfbdce604b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Nzg5NjcsIm5iZiI6MTcxMTk3ODY2NywicGF0aCI6Ii8xMjkzNTI2MTAvMzE3NjY0NTU0LTUwNzQyYzAxLTZhMDQtNDFhNS05ZTU5LTVlZGZiZGNlNjA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMzM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2YzMTlhZDczNzg0OGMzZjNkZWZjNWIxNzMzZTExNjdjMGFjNTBlZWY3ZDk1ODFlNDY0MzQ5YTUxMWNkMzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N8glk0yYw34muxcO3JXKndAuIUp1z7MFlsJsGN5R8co"> I'd like to ask about the "Mask" in the information regarding market indices (such as 000300) in your dataset. What does it refer to? Thank you!

**Comment by xbkaishui** [comment]
> Thank you for your attention to our work. We are not planning to publish the data infrastructure for explained reasons. If you need to process raw data, we highly recommend reusing the Qlib implementations. Here is the configuration:
> 
> > infer_processors:
> > - class: RobustZScoreNorm
> > kwargs:
> > fields_group: feature
> > clip_outlier: true
> > - class: Fillna
> > kwargs:
> > fields_group: feature
> > learn_processors:
> > - class: DropnaLabel
> > - class: DropExtremeLabel
> > kwargs:
> > percentile: 0.975
> > - class: CSZscoreNorm
> > kwargs:
> > fields_group: label
> 
> Please note that, except for `DropExtremeLabel`, the above configuration is used for many models in `qlib/examples/benchmarks` and we do use the Qlib implementations in producing the published dl_train, dl_valid, and dl_test. The `DropExtremeLabel` is implemented in our commercial codebase, which should be easy to implement in Qlib as well, since it obeys a simple rule to drop 2.5% of the highest/lowest labels.

hello， what is your commercial codebase price ?
