### ISSUE TITLE
How to view the DataFrame format of datasets generated using qlib?

### ISSUE THREAD

**Issue by ElonJustin7** [SJTU-Quant/MASTER#9]
Thank you for your excellent work! I would like to ask how to view the DataFrame format of **dl_train** generated by qlib, since it is a **TSDataSampler**, or how to generate and save **dl_train** **directly** without using the YAML format, similar to the dataset you provided in your code?
<img width="837" alt="截屏2024-05-07 16 01 35" src="https://github.com/SJTU-Quant/MASTER/assets/129352610/e2565a5d-a9ef-4354-9029-54d5788dc144">

My main purpose is to check whether the generated dataset is correct because YAML seems to be unable to view the generated DataFrame. Thank you!

**Comment by ElonJustin7** [comment]
By the way, where can I find the **saved** prediction scores and related metrics generated from **workflow_config_master_Alpha158.yaml**?

**Comment by ElonJustin7** [comment]
"The pkl file you provided can be viewed using .data to see the DataFrame, but the dl_train generated above using qlib cannot be viewed using .data and reports an error: 'TSDataSampler' object has no attribute 'data'."
<img width="1067" alt="截屏2024-05-07 16 35 55" src="https://github.com/SJTU-Quant/MASTER/assets/129352610/0188d6c0-83fc-4dc3-bb1b-afd58c1383e6">

**Comment by zhiyuan5986** [comment]
You can check the original code of `TSDataSampler` in `qlib.data.dataset.__init__`. In the last line of  `TSDataSampler.__init__()`, the official code `del self.data` to save memory. If you want to check the dataframe, you can uncomment `del self.data` and print `dl_train.data`.

**Comment by ElonJustin7** [comment]
Thank you for your response! I will give it a try

**Comment by bloomv** [comment]
修改了以下代码，也没有用：    print(dl_train.data) # ttributeError: 'TSDataSampler' object has no attribute 'data'
AttributeError: 'TSDataSampler' object has no attribute 'data'

        #del self.data  # save memory
